import type { Metadata } from "next"
import "./globals.css"
import { ThemeProvider } from "@/components/custom/theme-provider"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["vietnamese"], weight: ["100", "300"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
